### ISSUE TITLE
Is there a plan to support netsuite 2? 

### ISSUE THREAD

**Issue by nbenezri** [fivetran/dbt_netsuite_source#19]
if so, when?

I'm asking as with netsuite 2 I've got `transactionline` table, not `transaction_line`.
This is just an example, all the tables failed to build because of missing tables.
I'm using the latest dbt netsuite + netsuite source packages.

**Comment by nbenezri** [comment]
I see there is a PR waiting for it.
When is the plan for merging? we have a pretty large instance of netsuite2 on redshift and are willing to test if you like.
@fivetran-jamie @fivetran-joemarkiewicz

**Comment by fivetran-joemarkiewicz** [comment]
Hi @nbenezri we are planning to merge and release the PR you noted tomorrow! In the meantime, you are more than welcome to install the branch and give it a try. I would recommend taking a look at the CHANGELOG before running it in case you need to make any configuration changes on your end.

To try the working branch, you can use the following in your packages.yml
```yml
packages:
  - git: https://github.com/fivetran/dbt_netsuite_source.git
    revision: feature/netsuite2
    warn-unpinned: false
```

**Comment by nbenezri** [comment]
great timing :D 
I will wait the extra day!

**Comment by fivetran-joemarkiewicz** [comment]
@nbenezri Netsuite2 support is now live in the latest release of the package! Feel free to refer to the updated README and release notes for details on how to leverage Netsuite2 compatibility.
