### ISSUE TITLE
[Bug] Persist Item and Vendor Passthrough Columns for Netsuite2

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_netsuite_source#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

PR #23 added passthrough columns for items and vendors into the Netsuite1 models. However, the same changes were not applied to the Netsuite2 models in the package. The passthrough columns should work as intended for both the Netsuite and Netsuite2 forms of this package.

### Relevant error log or model output

```shell
M/A
```

### Expected behavior

Passthrough columns defined for items and vendors persist when using both Netsuite and Netsuite2 models.

### dbt Project configurations

vars:
    vendors_pass_through_columns: 
        - name: "vendors_custom_field"
          alias: "vendors_field"
    items_pass_through_columns: 
        - name: "items_custom_field"
          alias: "items_field"

### Package versions

v0.6.0

### What database are you using dbt with?

postgres, redshift, snowflake, bigquery, databricks

### dbt Version

v1.3.1

### Additional Context

The code within the [stg_netsuite__items](https://github.com/rpalloni/dbt_netsuite_source/blob/096bda8abcbc0757c64f4867a843f7a6d60a5456/models/netsuite/stg_netsuite__items.sql#L39-L40) and [stg_netsuite__vendors](https://github.com/fivetran/dbt_netsuite_source/blob/541bd4ed86c9769a2fd702a6058c4b4d753ec879/models/netsuite/stg_netsuite__vendors.sql#L39-L40) can simply be copy/pasted into the Netsuite2 counterpart models to address this issue.

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-jamie** [comment]
i noticed that these passthrough columns are not in the transform package, though these tables are indeed brought into the transaction_details model.... should we also add the vendor/item passthrough columns to the transform package while we're at it? @fivetran-joemarkiewicz

**Comment by fivetran-joemarkiewicz** [comment]
Following our conversation offline, let's plan to not persist the passthrough columns through for now. However, if we could create a complimentary FR to track this idea that would be great!

**Comment by fivetran-joemarkiewicz** [comment]
Closing as this has been addressed in the above PRs.
