### ISSUE TITLE
[Feature] Enable teams to configure additional columns for all source models

### ISSUE THREAD

**Issue by FrankTub** [fivetran/dbt_netsuite_source#50]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

In the [Netsuite](https://github.com/fivetran/dbt_netsuite) package it is possible to pass some additional columns for the end models that are created by that package. This is possible for some of the tables, but not for all source tables that are used in `dbt_netsuite_source`. Furthermore, not all columns that I would like to use in my own downstream models are relevant for the end models created by the [Netsuite](https://github.com/fivetran/dbt_netsuite) package.

Therefore I think it would be really beneficial to be able to add columns to the netsuite source models directly without impacting the models in [Netsuite](https://github.com/fivetran/dbt_netsuite). This allows for more flexibility in custom development for teams that have other requirements without the need for a new PR for every small change. Additionally this helps when there are customizations made in Netsuite that are very business specific.

### Describe alternatives you've considered

- Opening a PR
- Creating your own custom base model

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

Let me know what you guys thing, and if you think it is a good idea I will pick it up.

**Comment by fivetran-avinash** [comment]
Hi @FrankTub ! Thanks for bringing this to request to our attention.

I think our team wants to avoid overengineering passthrough columns on tables that don't really require them, as that is a pretty hefty feature to test and validate. I don't believe we'd want to configure passthrough functionality for all source models unless you absolutely need them on every table. 

Maybe let's start with your specific use case. If you were to create a PR, what tables do you think you'd need to add passthrough functionality for? I'd recommend starting there, and then submitting a PR that we can review!

Let us know if you have any questions!

**Comment by FrankTub** [comment]
Opened a PR for my current use case: https://github.com/fivetran/dbt_netsuite_source/pull/51

**Comment by fivetran-avinash** [comment]
Hi @FrankTub ! Sorry, our team is involved in a company event at the moment, we should have some time to take a look at this tomorrow.

**Comment by fivetran-avinash** [comment]
Hi @FrankTub! Thanks for your patience. Your PR is now merged and the newest release is now live on the dbt hub. https://hub.getdbt.com/fivetran/netsuite_source/latest/ 

Try it out and let us know if everything works as anticipated, and of course reach out to us if you have any questions or concerns. 

I will close this issue out, but here's to working more together in the future! Thanks again 😃 .
