### ISSUE TITLE
FEATURE - Add Passthrough Columns to Locations Model

### ISSUE THREAD

**Issue by oreoana** [fivetran/dbt_netsuite_source#9]
**Are you a Fivetran customer?** 
Yes -- Blue Bottle Coffee

**Is your feature request related to a problem? Please describe.**
I'd like to be able to add pass-through columns to some of the Netsuite staging models, specifically `stg_netsuite__locations`.

**Describe the solution you'd like**
Be able to specify pass-through columns for the locations staging model in the `netsuite_source` package using the existing approach here: https://github.com/fivetran/dbt_netsuite_source#configuration

**Describe alternatives you've considered**
Build our own Netsuite locations staging model.

**Please indicate the level of urgency and business impact of this request** 
Medium -- would allow us to set up a better infrastructure for our locations data pipeline.

**Are you interested in contributing to this package?** 
- [X] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
@oreoana I wanted to provide an FYI that the `locations_pass_through_columns` variable was included in the latest release of the `dbt_netsuuite_source` package. You can expect the package to be live on the dbt hub at the top of the hour.

Thanks again for opening this issue! 😄

**Comment by oreoana** [comment]
@fivetran-joemarkiewicz great! Thanks so much for this!
